### ISSUE TITLE
gem doesn't match github code?

### ISSUE THREAD

**Issue by runecalico** [mikian/rubocop-junit-formatter#14]
After much annoyance and swearing on why I couldn't get any output from the junit formatter gem when there where no offenses, and yet the github code *looks* like it should output... I looked at the gem that I got from rubygems.org... and it doesn't match what's in github.

This line I think is the culprit..
        return if offences.empty?

right here..
      def file_finished(file, offences)
        return if offences.empty?

        # One test case per cop per file

Does the gem need to be updated, or ???

**Comment by mikian** [comment]
New release done on rubygems.
