### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by nambrot** [mikian/rubocop-junit-formatter#4]
I've been trying to use the Junit formatter, but it doesn't seem like it works for by running `bundle exec rubocop --format RuboCop::Formatter::JUnitFormatter`. What am I missing?

**Comment by rbxd** [comment]
Not sure about the designated way, but I'm using `-r` command line option to require arbitrary Ruby files.

Example:

``` bash
JUNIT_FMT_PATH="`gem path rubocop-junit-formatter`/lib/rubocop/formatter/junit_formatter.rb"

rubocop -r $JUNIT_FMT_PATH --format RuboCop::Formatter::JUnitFormatter $COOKBOOK_PATH
```

(you would need [gem path](https://rubygems.org/gems/gem-path/))
